export const CAMADAS_TOTAL_REQUEST = "camada/CAMADA_TOTAL_REQUEST";
export const CAMADAS_TOTAL_SUCCESS = "camada/CAMADA_TOTAL_SUCCESS";
export const CAMADAS_TOTAL_FAILURE = "camada/CAMADA_TOTAL_FAILURE";

export const CAMADAS_REQUEST = "camada/CAMADAS_REQUEST";
export const CAMADAS_SUCCESS = "camada/CAMADAS_SUCCESS";
export const CAMADAS_FAILURE = "camada/CAMADAS_FAILURE";

export const CAMADA_REQUEST = "camada/CAMADA_REQUEST";
export const CAMADA_SUCCESS = "camada/CAMADA_SUCCESS";
export const CAMADA_FAILURE = "camada/CAMADA_FAILURE";

export const SALVAR_CAMADA_REQUEST = "camada/SALVAR_CAMADA_REQUEST";
export const SALVAR_CAMADA_SUCCESS = "camada/SALVAR_CAMADA_SUCCESS";
export const SALVAR_CAMADA_FAILURE = "camada/SALVAR_CAMADA_FAILURE";

export const EXCLUIR_CAMADA_REQUEST = "camada/EXCLUIR_CAMADA_REQUEST";
export const EXCLUIR_CAMADA_SUCCESS = "camada/EXCLUIR_CAMADA_SUCCESS";
export const EXCLUIR_CAMADA_FAILURE = "camada/EXCLUIR_CAMADA_FAILURE";

export const UPDATE_CAMADA_REQUEST = "camada/UPDATE_CAMADA_REQUEST";
export const UPDATE_CAMADA_SUCCESS = "camada/UPDATE_CAMADA_SUCCESS";
export const UPDATE_CAMADA_FAILURE = "camada/UPDATE_CAMADA_FAILURE";

export const CAMADAS_ATIVAS_REQUEST = "camada/CAMADAS_ATIVAS_REQUEST";
export const CAMADAS_ATIVAS_SUCCESS = "camada/CAMADAS_ATIVAS_SUCCESS";
export const CAMADAS_ATIVAS_FAILURE = "camada/CAMADAS_ATIVAS_FAILURE";